import { chromium } from '/Volumes/Spare/npm/global/lib/node_modules/@playwright/mcp/node_modules/playwright/index.mjs';
const CLOAK = '/Users/m/.cloakbrowser/chromium-145.0.7632.109.2/Chromium.app/Contents/MacOS/Chromium';
const [uid, pwd] = process.argv[2].split(':');
const browser = await chromium.launch({ headless: false, executablePath: CLOAK, args: ['--window-size=1440,900'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const posts = [];
page.on('request', r => { if (r.method() === 'POST' && /gateway/.test(r.url())) posts.push({ url: r.url().slice(0, 160), post: (r.postData() || '').slice(0, 400) }); });
page.on('response', async r => { if (r.request().method() === 'POST' && /gateway/.test(r.url())) { let body = ''; try { body = (await r.text()).slice(0, 300); } catch {} console.log('POST RESP', r.status(), r.url().slice(0, 130), '|', body.replace(/\n/g, ' ')); } });
await page.goto('https://citytouch.com.bd/', { waitUntil: 'load', timeout: 60000 });
await page.waitForTimeout(6000);
await page.click('input[name="User ID"]'); await page.type('input[name="User ID"]', uid, { delay: 40 });
await page.click('input[name="Password"]'); await page.type('input[name="Password"]', pwd, { delay: 40 });
await page.waitForTimeout(800);
console.log('clicking Login...');
await page.click('button:has-text("Login")');
await page.waitForTimeout(9000);
console.log('URL now:', page.url());
const after = await page.evaluate(() => ({ url: location.href, bodyText: document.body.innerText.replace(/\s+/g, ' ').slice(0, 350) }));
console.log('AFTER:', JSON.stringify(after, null, 1));
console.log('POSTS CAPTURED:', JSON.stringify(posts, null, 1));
await browser.close();
